name: Continous Integration and Deployment

on:
  push:
    branches: [ master ]

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: |
            /opt/hostedtoolcache/flutter
            build/test_cache
          key: ${{ runner.os }}-flutter

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Run backend in background
        run: |
          podman run -d \
            -p 8080:8080 \
            registry.digitalocean.com/krasnov/fitness-driven-monolith:6afeac08b463e5faaeccbad2729a56c45907fede
          sleep 1

      - name: Run tests
        run: flutter test

      - name: Log into pub.dev
        run: echo $CREDENTIALS | base64 -d > $PUB_CACHE/credentials.json
        env:
          CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}

      - name: Publish package to pub.dev
        if: false
        run: echo y | flutter pub publish